---
- name: Configuração do VPN-server
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Instala pacotes essenciais
      apt:
        name:
          - build-essential
          - libreadline-dev
          - libssl-dev
          - libncurses5-dev
          - ufw
        state: present
        update_cache: yes

    - name: Baixa SoftEther
      get_url:
        url: "https://www.softether-download.com/files/softether/v4.44-9807-rtm-2025.04.16-tree/Linux/SoftEther_VPN_Server/64bit_-_Intel_x64_or_AMD64/softether-vpnserver-v4.44-9807-rtm-2025.04.16-linux-x64-64bit.tar.gz"
        dest: /usr/local/softether-vpnserver.tar.gz
        mode: '0644'

    - name: Extrai SoftEther
      unarchive:
        src: /usr/local/softether-vpnserver.tar.gz
        dest: /usr/local/
        remote_src: yes

    - name: Compilar SoftEther
      shell: |
        make clean || true
        make
      args:
        chdir: /usr/local/vpnserver

    - name: Ajusta permissões do diretório
      file:
        path: /usr/local/vpnserver
        owner: root
        group: root
        recurse: yes
        mode: "0755"

    - name: Permitir execução dos binários
      file:
        path: "/usr/local/vpnserver/{{ item }}"
        mode: "0700"
      loop:
        - vpnserver
        - vpncmd

    - name: Criar serviço systemd SoftEther
      copy:
        dest: /etc/systemd/system/softether-vpnserver.service
        content: |
          [Unit]
          Description=SoftEther VPN Server
          After=network.target

          [Service]
          Type=forking
          ExecStart=/usr/local/vpnserver/vpnserver start
          ExecStop=/usr/local/vpnserver/vpnserver stop
          ExecReload=/usr/local/vpnserver/vpnserver restart
          WorkingDirectory=/usr/local/vpnserver/
          User=root
          Group=root
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
      notify: Reload systemd

    - name: Habilitar e iniciar SoftEther
      systemd:
        name: softether-vpnserver
        enabled: yes
        state: started

    - name: Abrir portas no firewall
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - "443"
        - "5555"
        - "992"
        - "1194"

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Restart vpnserver
      systemd:
        name: softether-vpnserver
        state: restarted
